In [18]:
import pandas as pd

DATA_INPUT_PATH = "/home/paula/Documentos/pmorenofajardo87/NOCTUAMED/noctuamed_rafa/transmisiones_a_csv/transmisiones_anonimizadas_gem/estandarizados/omop_standardized_data.csv"
DATA_INFO = "/home/paula/Documentos/pmorenofajardo87/NOCTUAMED/noctuamed_rafa/transmisiones_a_csv/data_analysis/omop_data_info.csv"

This notebook will do some conversion in data in order to normalize affterwards

## Corrections in Categorical data

In [19]:
omop_data_info_df = pd.read_csv(DATA_INFO)
data = pd.read_csv(DATA_INPUT_PATH)

In [20]:
omop_data_info_df.head()

,Unnamed: 0,Field,Data type,Expected range,Manufacturers,Sample of Values,Numbre of Values,is_date,Date_format,Date_only_one_format,...,is_categorical,is_numeric,Number of Numeric Values,Min,Max,Percentage of values within range,% are boolean,Number of Boolean Values,is_boolean,boolean_formats
0,0,MDC_IDC_SESS_DTM,Datetime,NaN,p1_abbott,"['20250311040016', '20250325060035', '20250318...",3,True,{'%Y%m%d%H%M%S'},True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,MDC_IDC_SESS_TYPE,Varchar,NaN,p1_abbott,['RemoteScheduled'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,MDC_IDC_DEV_TYPE,Varchar,NaN,p1_abbott,['IPG'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,MDC_IDC_DEV_MFG,Varchar,NaN,p1_abbott,['Abbott'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,MDC_IDC_DEV_MODEL,Varchar,NaN,p1_abbott,['2272 Assurity MRI(TM)'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
omop_data_info_df[omop_data_info_df['is_text'] == True]

,Unnamed: 0,Field,Data type,Expected range,Manufacturers,Sample of Values,Numbre of Values,is_date,Date_format,Date_only_one_format,...,is_categorical,is_numeric,Number of Numeric Values,Min,Max,Percentage of values within range,% are boolean,Number of Boolean Values,is_boolean,boolean_formats
1,1,MDC_IDC_SESS_TYPE,Varchar,NaN,p1_abbott,['RemoteScheduled'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,MDC_IDC_DEV_TYPE,Varchar,NaN,p1_abbott,['IPG'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,MDC_IDC_DEV_MFG,Varchar,NaN,p1_abbott,['Abbott'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,MDC_IDC_DEV_MODEL,Varchar,NaN,p1_abbott,['2272 Assurity MRI(TM)'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,MDC_IDC_DEV_SERIAL,Varchar,NaN,p1_abbott,['6700726'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,MDC_IDC_MSMT_BATTERY_STATUS,Varchar,NaN,p1_abbott,['754116^MDC_IDC_ENUM_BATTERY_STATUS_MOS^MDC'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p1_abbott,['DDD'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p1_abbott,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p1_abbott,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Varchar,Unipolar/Bipolar,p1_abbott,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Varchar,Unipolar/Bipolar,p1_abbott,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,MDC_IDC_MSMT_LEADCHNL_RA_LEAD_CHANNEL_STATUS,Varchar,"OK, fallo, alerta",p1_abbott,['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,Varchar,"OK, fallo, alerta",p1_abbott,['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,50,CLINIC_NAME,Varchar,Nombre del centro médico,p2_biotronik,['Hospital Universitario de Gran Canaria Dr. N...,1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,51,MANUFACTURER_PRIORITY,Varchar/Integer,Interno; sin rango definido,p2_biotronik,['Amarillo'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,53,MDC_IDC_SESS_TYPE,Varchar,NaN,p2_biotronik,['Remote'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,54,MDC_IDC_DEV_TYPE,Varchar,NaN,p2_biotronik,['IPG'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,55,MDC_IDC_DEV_MFG,Varchar,NaN,p2_biotronik,['Biotronik'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,56,MDC_IDC_DEV_MODEL,Varchar,NaN,p2_biotronik,"['Epyra 6 SR-T', 'Enitra 6 SR-T']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57,MDC_IDC_DEV_SERIAL,Varchar,NaN,p2_biotronik,"['68948906', '1000096403', '70402737']",4,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,60,MDC_IDC_MSMT_BATTERY_STATUS,Varchar,NaN,p2_biotronik,['MOS'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,62,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p2_biotronik,"['VVIR', 'VVI']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,65,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p2_biotronik,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,68,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,Varchar,"OK, fallo, alerta",p2_biotronik,['Null'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,75,MDC_IDC_DEV_TYPE,Varchar,NaN,p3_boston_scientific,"['TRC-D', 'DAI', 'S-ICD']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,76,MDC_IDC_DEV_MFG,Varchar,NaN,p3_boston_scientific,['Boston Scientific'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,77,MDC_IDC_DEV_MODEL,Varchar,NaN,p3_boston_scientific,"['RESONATE CRT-D', 'VIGILANT EL ICD', 'EMBLEM ...",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,78,MDC_IDC_DEV_SERIAL,Varchar,NaN,p3_boston_scientific,"['526288', '619014', '140574']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,80,MDC_IDC_MSMT_BATTERY_STATUS,Varchar,NaN,p3_boston_scientific,['OK Tiempo aprox. para el explante:> 8 años d...,3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,82,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p3_boston_scientific,['DDD'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,90,MDC_IDC_SESS_TYPE,Varchar,NaN,p4_medtronic,['Remote'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,91,MDC_IDC_DEV_TYPE,Varchar,NaN,p4_medtronic,['Pacemaker'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,92,MDC_IDC_DEV_MFG,Varchar,NaN,p4_medtronic,['Medtronic'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,93,MDC_IDC_DEV_MODEL,Varchar,NaN,p4_medtronic,['ADDR01'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,94,MDC_IDC_DEV_SERIAL,Varchar,NaN,p4_medtronic,"['NWB871343S', 'NWB083596G']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,96,MDC_IDC_MSMT_BATTERY_STATUS,Varchar,NaN,p4_medtronic,['OK'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,99,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p4_medtronic,"['DDDR', 'DDD']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,106,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p4_medtronic,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,107,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p4_medtronic,['BI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,110,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Varchar,Unipolar/Bipolar,p4_medtronic,['UNI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,111,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Varchar,Unipolar/Bipolar,p4_medtronic,['UNI'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,124,MDC_IDC_SET_ZONE_TYPE,Varchar,"VT, VF, etc.",p4_medtronic,['ATRIAL_FIBRILLATION'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,131,MDC_IDC_DEV_TYPE,Varchar,NaN,p5_microport,"['ICD', 'Pacemaker']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,132,MDC_IDC_DEV_MFG,Varchar,NaN,p5_microport,['Microport'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,133,MDC_IDC_DEV_MODEL,Varchar,NaN,p5_microport,"['TALENTIA DF4 VR 3240', 'ULYS DF4 DR 2540', '...",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,134,MDC_IDC_DEV_SERIAL,Varchar,NaN,p5_microport,"['317JQ035', '221DU181', '025GB06C']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,137,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p5_microport,"['VVI', 'SafeR', 'DDDR']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,146,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p5_microport,['BI}'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,147,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Varchar,Unipolar/Bipolar,p5_microport,['BI}'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,150,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Varchar,Unipolar/Bipolar,p5_microport,['BI}'],1,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,151,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Varchar,Unipolar/Bipolar,p5_microport,"['BI}', 'UNI']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Lets compare Expected range attribute (given by cloude or chat gpt with Used Values

In [22]:
omop_data_info_df[(omop_data_info_df['is_text'] == True)&(omop_data_info_df['Expected range'] != 'NaN')][['Expected range', 'Used Values']]

,Expected range,Used Values
1,NaN,['RemoteScheduled']
2,NaN,['IPG']
3,NaN,['Abbott']
4,NaN,['2272 Assurity MRI(TM)']
5,NaN,['6700726']
8,NaN,['754116^MDC_IDC_ENUM_BATTERY_STATUS_MOS^MDC']
13,NaN,['DDD']
19,Unipolar/Bipolar,['BI']
20,Unipolar/Bipolar,['BI']
23,Unipolar/Bipolar,['BI']
24,Unipolar/Bipolar,['BI']
27,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
28,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
50,Nombre del centro médico,['Hospital Universitario de Gran Canaria Dr. N...
51,Interno; sin rango definido,['Amarillo']
53,NaN,['Remote']
54,NaN,['IPG']
55,NaN,['Biotronik']
56,NaN,"['Epyra 6 SR-T', 'Enitra 6 SR-T']"
57,NaN,"['68948906', '1000096403', '70402737', '699860..."
60,NaN,['MOS']
62,NaN,"['VVIR', 'VVI']"
65,Unipolar/Bipolar,['BI']
68,"OK, fallo, alerta",['Null']
75,NaN,"['TRC-D', 'DAI', 'S-ICD']"
76,NaN,['Boston Scientific']
77,NaN,"['RESONATE CRT-D', 'VIGILANT EL ICD', 'EMBLEM ..."
78,NaN,"['526288', '619014', '140574']"
80,NaN,['OK Tiempo aprox. para el explante:> 8 años d...
82,NaN,['DDD']
90,NaN,['Remote']
91,NaN,['Pacemaker']
92,NaN,['Medtronic']
93,NaN,['ADDR01']
94,NaN,"['NWB871343S', 'NWB083596G']"
96,NaN,['OK']
99,NaN,"['DDDR', 'DDD']"
106,Unipolar/Bipolar,['BI']
107,Unipolar/Bipolar,['BI']
110,Unipolar/Bipolar,['UNI']
111,Unipolar/Bipolar,['UNI']
124,"VT, VF, etc.",['ATRIAL_FIBRILLATION']
131,NaN,"['ICD', 'Pacemaker']"
132,NaN,['Microport']
133,NaN,"['TALENTIA DF4 VR 3240', 'ULYS DF4 DR 2540', '..."
134,NaN,"['317JQ035', '221DU181', '025GB06C']"
137,NaN,"['VVI', 'SafeR', 'DDDR']"
146,Unipolar/Bipolar,['BI}']
147,Unipolar/Bipolar,['BI}']
150,Unipolar/Bipolar,['BI}']
151,Unipolar/Bipolar,"['BI}', 'UNI']"

we will start by existing expected values

In [23]:
omop_data_info_df[(omop_data_info_df['is_text'] == True) & (pd.notna(omop_data_info_df['Expected range']))][
    ['Field', 'Expected range', 'Used Values']]

,Field,Expected range,Used Values
19,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI']
20,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
23,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['BI']
24,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,['BI']
27,MDC_IDC_MSMT_LEADCHNL_RA_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
28,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
50,CLINIC_NAME,Nombre del centro médico,['Hospital Universitario de Gran Canaria Dr. N...
51,MANUFACTURER_PRIORITY,Interno; sin rango definido,['Amarillo']
65,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
68,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['Null']
106,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI']
107,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
110,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['UNI']
111,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,['UNI']
124,MDC_IDC_SET_ZONE_TYPE,"VT, VF, etc.",['ATRIAL_FIBRILLATION']
146,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI}']
147,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI}']
150,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['BI}']
151,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,"['BI}', 'UNI']"

### Unipolar/Bipolar
 seems that Unipolar/Bipolar is always BI/UNI OR B/U

In [24]:
unipolar_bipolar = omop_data_info_df[(omop_data_info_df['is_text'] == True) & (pd.notna(omop_data_info_df['Expected range'])&(omop_data_info_df['Expected range'] == 'Unipolar/Bipolar'))][
['Field', 'Expected range', 'Used Values']]
unipolar_bipolar

,Field,Expected range,Used Values
19,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI']
20,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
23,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['BI']
24,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,['BI']
65,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
106,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI']
107,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI']
110,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['UNI']
111,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,['UNI']
146,MDC_IDC_SET_LEADCHNL_RA_SENSING_POLARITY,Unipolar/Bipolar,['BI}']
147,MDC_IDC_SET_LEADCHNL_RV_SENSING_POLARITY,Unipolar/Bipolar,['BI}']
150,MDC_IDC_SET_LEADCHNL_RA_PACING_POLARITY,Unipolar/Bipolar,['BI}']
151,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Unipolar/Bipolar,"['BI}', 'UNI']"

In [25]:
words = unipolar_bipolar['Used Values'].to_list()
unique_words = set([item.strip("[]'").replace("'", "") for item in words])
unique_words

{'BI', 'BI}', 'BI}, UNI', 'UNI'}

In [26]:
replace_dict  = {'B':'BI',
            'U' : 'UNI'}

In [27]:
omop_data_info_df.columns

Index(['Unnamed: 0', 'Field', 'Data type', 'Expected range', 'Manufacturers',
       'Sample of Values', 'Numbre of Values', 'is_date', 'Date_format',
       'Date_only_one_format', 'is_text', 'Used Values', '% valid varchar',
       'Valid varchar count', 'Total varchar values', 'is_categorical',
       'is_numeric', 'Number of Numeric Values', 'Min', 'Max',
       'Percentage of values within range', '% are boolean',
       'Number of Boolean Values', 'is_boolean', 'boolean_formats'],
      dtype='object')

In [28]:
cols = unipolar_bipolar['Field'].to_list()
clean_data = data.copy()
for col in cols:
    if col in clean_data.columns:
        clean_data[col] = clean_data[col].replace(replace_dict)



# # Selecciona las filas donde 'Field' está en 'cols'
# mask = omop_data_info_df['Field'].isin(cols)
# # Asigna True en la columna 'is_categorical' para estas filas
# omop_data_info_df.loc[mask, 'is_categorical'] = True
# # Opcional: también puedes asignar otros valores o realizar más operaciones en este filtro
# # Como en tu código, también puedes actualizar otras columnas en el mismo filtro
# omop_data_info_df.loc[mask, 'Expected range'] = 'UNI/BI'

l### Ok, Fallo, Alerta

In [29]:
ok_fallo_alerta = omop_data_info_df[(omop_data_info_df['is_text'] == True) & (pd.notna(omop_data_info_df['Expected range'])&(omop_data_info_df['Expected range'] == 'OK, fallo, alerta'))][
['Field', 'Expected range', 'Used Values']]
ok_fallo_alerta

,Field,Expected range,Used Values
27,MDC_IDC_MSMT_LEADCHNL_RA_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
28,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['754242^MDC_IDC_ENUM_CHANNEL_STATUS_Null^MDC']
68,MDC_IDC_MSMT_LEADCHNL_RV_LEAD_CHANNEL_STATUS,"OK, fallo, alerta",['Null']

clean_data.to_csv ('clean_omop_standardized_data.csv', index = False, header=True)no parece que se pueda llegar a más correcciones por ahora

## Corrections in numerical data

In [30]:
omop_data_info_df[(omop_data_info_df['Data type'] == 'Numeric') & (omop_data_info_df['is_numeric'] != True)][['Field','Manufacturers', 'Expected range', 'Sample of Values']]

,Field,Manufacturers,Expected range,Sample of Values
86,MDC_IDC_SET_LEADCHNL_RA_SENSING_SENSITIVITY,p3_boston_scientific,0.5–5.0 mV,['AGC 0.25']
87,MDC_IDC_SET_LEADCHNL_RV_SENSING_SENSITIVITY,p3_boston_scientific,0.5–5.0 mV,['AGC 0.6']
88,MDC_IDC_SET_LEADCHNL_LV_SENSING_SENSITIVITY,p3_boston_scientific,0.5–5.0 mV,['AGC 1.0']

There is one Value that shuold be numeric but there is AGC before number.

Lets see same omop attribute for others manufacturers

In [31]:
data['MDC_IDC_SET_LEADCHNL_RA_SENSING_SENSITIVITY'].unique()

array(['0.5', nan, 'AGC 0.25', '0.50', '0.35', '0.4', '1.00'],
      dtype=object)

It seems that only abbot use AGC before the number

More insight needs to be done after correcting this case

In [32]:
clean_data.to_csv('clean_omop_standardized_data.csv', index=False, header=True)
omop_data_info_df.to_csv('omop_data_info.csv',index=False, header=True)

In [33]:
omop_data_info_df[omop_data_info_df['is_categorical'] == True]

,Unnamed: 0,Field,Data type,Expected range,Manufacturers,Sample of Values,Numbre of Values,is_date,Date_format,Date_only_one_format,...,is_categorical,is_numeric,Number of Numeric Values,Min,Max,Percentage of values within range,% are boolean,Number of Boolean Values,is_boolean,boolean_formats
56,56,MDC_IDC_DEV_MODEL,Varchar,NaN,p2_biotronik,"['Epyra 6 SR-T', 'Enitra 6 SR-T']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57,MDC_IDC_DEV_SERIAL,Varchar,NaN,p2_biotronik,"['68948906', '1000096403', '70402737']",4,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,62,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p2_biotronik,"['VVIR', 'VVI']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,75,MDC_IDC_DEV_TYPE,Varchar,NaN,p3_boston_scientific,"['TRC-D', 'DAI', 'S-ICD']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,77,MDC_IDC_DEV_MODEL,Varchar,NaN,p3_boston_scientific,"['RESONATE CRT-D', 'VIGILANT EL ICD', 'EMBLEM ...",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,78,MDC_IDC_DEV_SERIAL,Varchar,NaN,p3_boston_scientific,"['526288', '619014', '140574']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,80,MDC_IDC_MSMT_BATTERY_STATUS,Varchar,NaN,p3_boston_scientific,['OK Tiempo aprox. para el explante:> 8 años d...,3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,94,MDC_IDC_DEV_SERIAL,Varchar,NaN,p4_medtronic,"['NWB871343S', 'NWB083596G']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,99,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p4_medtronic,"['DDDR', 'DDD']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,131,MDC_IDC_DEV_TYPE,Varchar,NaN,p5_microport,"['ICD', 'Pacemaker']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,133,MDC_IDC_DEV_MODEL,Varchar,NaN,p5_microport,"['TALENTIA DF4 VR 3240', 'ULYS DF4 DR 2540', '...",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,134,MDC_IDC_DEV_SERIAL,Varchar,NaN,p5_microport,"['317JQ035', '221DU181', '025GB06C']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,137,MDC_IDC_SET_BRADY_MODE,Varchar,NaN,p5_microport,"['VVI', 'SafeR', 'DDDR']",3,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,151,MDC_IDC_SET_LEADCHNL_RV_PACING_POLARITY,Varchar,Unipolar/Bipolar,p5_microport,"['BI}', 'UNI']",2,NaN,NaN,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Vuelvo a crear el fichero omop_data_info.csv from clean data

In [34]:
from helpers.utils import analizar_datos_omop
DATA_CLEAN_INPUT_PATH = "/home/paula/Documentos/pmorenofajardo87/NOCTUAMED/noctuamed_rafa/transmisiones_a_csv/data_analysis/clean_omop_standardized_data.csv"
omop_standardized = pd.read_csv(DATA_CLEAN_INPUT_PATH)
omop_fields = pd.read_csv("OMOP_fields_merged.csv")
omop_field_names = omop_fields['OMOP Field'].tolist()
manufacturer_codes = omop_standardized['manufacturer_code'].unique()
omop_data_info_df = analizar_datos_omop(
    omop_standardized=omop_standardized,
    manufacturer_codes=manufacturer_codes,
    omop_field_names=omop_field_names,
    omop_fields=omop_fields
)
omop_data_info_df.to_csv('omop_data_info.csv')

==================================================
Analyzing manufacturer: p1_abbott
==================================================
Number of records: 6
Non-empty columns: 53
Non-OMOP columns:
- source_file
- manufacturer_code
- patient_id_pid3

==================================================
Analyzing manufacturer: p2_biotronik
==================================================
Number of records: 8
Non-empty columns: 26
Non-OMOP columns:
- source_file
- manufacturer_code

==================================================
Analyzing manufacturer: p3_boston_scientific
==================================================
Number of records: 6
Non-empty columns: 19
Non-OMOP columns:
- source_file
- manufacturer_code
- patient_id_pid2
- patient_id_pid3
⚠️ Warning: p3_boston_scientific - MDC_IDC_SET_LEADCHNL_RA_SENSING_SENSITIVITY expected numeric but has parsing issues.
⚠️ Warning: p3_boston_scientific - MDC_IDC_SET_LEADCHNL_RV_SENSING_SENSITIVITY expected numeric but has parsing issues.
⚠️ Warning: p3_boston_scientific - MDC_IDC_SET_LEADCHNL_LV_SENSING_SENSITIVITY expected numeric but has parsing issues.

==================================================
Analyzing manufacturer: p4_medtronic
==================================================
Number of records: 4
Non-empty columns: 45
Non-OMOP columns:
- source_file
- manufacturer_code
- patient_id_pid2
- patient_id_pid3

==================================================
Analyzing manufacturer: p5_microport
==================================================
Number of records: 6
Non-empty columns: 34
Non-OMOP columns:
- source_file
- manufacturer_code